name: Deploy Discord Bot

on:
  push:
    branches:
      - main  # Ou a branch que você quiser

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o repositório
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Instalar dependências
      run: npm install

    - name: Rodar o bot
      run: npm start
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # Usando variável secreta para o token
