name: Deploy Discord Bot

on:
  push:
    branches:
      - main  # Use a branch onde seu código vai estar (por exemplo, "main" ou "master")

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o repositório
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # A versão do Node.js que você está usando

    - name: Instalar dependências
      run: npm install

    - name: Rodar o bot
      run: npm start
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # Variável secreta com seu token do bot
